config/routes.rb
Rails.application.routes.draw do
  get 'templates/serve'

  get '/home' => 'static_pages#home'
  get '/templates/:name' => "templates#serve", as: 'template'
  get '/profile/:id' => "users#profile", as: 'profile'
  post '/ban' => 'users#ban', as: 'ban'
  devise_for :users
  root 'static_pages#data'
  resources :items do
    resources :images
  end
  resources :projections, only: :create
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  status      :string(255)      default("projection")
#  link        :string(255)
#  user_id     :integer
#  max_price   :decimal(7, 2)
#  min_price   :decimal(7, 2)
#  created_at  :datetime
#  updated_at  :datetime
#

class Item < ActiveRecord::Base
  belongs_to :artist, class_name: "User", foreign_key: "user_id"
  validates_presence_of :artist, :title, :description, :status
  has_many :projections, dependent: :destroy
  has_many :users, through: :projections
  has_many :images, dependent: :destroy, inverse_of: :item
  accepts_nested_attributes_for :images

  after_update :send_email
  STATUS = %i[projection closed hidden]

  scope :old, -> {where("created_at < ?", 7.days.ago)}

  def send_email
    if status_changed?
      self.projections.each do |p|
        ItemMailer.item_email_update(p).deliver
      end
    end
  end

  def status_update
    if created_at < 7.days.ago
      self.status = 'closed'
      save!
    end
  end

  def self.recently_updated
    #Item.all.sort_by(&:updated_at).last(3).reverse
    updated = Item.order(:updated_at => :desc).limit 3
    hash = []
    updated.each do |up|
      hash << {title: up.title, image: up.images.first.picture.url(:medium), id: up.id}
    end 
    hash
  end

  def self.popular
    popular = Item.all.sort_by{|a|a.projections.count}.last(3).reverse
    hash = []
    popular.each do |up|
      hash << {title: up.title, image: up.images.first.picture.url(:medium), id: up.id}
    end 
    hash
  end

  def self.new_items
    # Item.all.sort_by(&:created_at).last(3).reverse
    new = Item.order(:created_at => :desc).limit 3
    hash = []
    new.each do |up|
      hash << {title: up.title, image: up.images.first.picture.url(:medium), id: up.id}
    end 
    hash
  end

  def average
    return "No Projected Prices" if projections.blank?
    avg = projections.where(price: min_price.to_f .. max_price.to_f )
    unless avg.blank?
      avg.map(&:price).inject(&:+)/(avg.count) 
    else
      "All Projected Prices Are Outside of Your Range"
    end
  end

  def entire_average
    return "No Projected Prices" if projections.blank?
    projections.map(&:price).inject(&:+)/projections.count
  end

  def days_remaining
    days = created_at + 7.days
    t = days - Time.now
    mm, ss = t.divmod(60)
    hh, mm = mm.divmod(60)
    dd, hh = hh.divmod(24)
    dd
  end

  def is_old
    Item.old.include?(self)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :get_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.includes(:images, :projections).all
  end

  def show
    @projection = current_user.projections.new if current_user
  end

  def new
    authorize! :project, Item
    @item = current_user.posted_items.new
    @item.images.build
    # ^ Used to Build the Nested Resource Form
  end

  def create
    authorize! :create, Item
    @item = current_user.posted_items.create(item_params)
    if @item.save!
      redirect_to "/#/items/#{@item.id}", notice: "Item was Successfully Created"
    else
      flash[:danger] = 'Item could not be saved'
      render :new
    end
  end

  def edit
    authorize! :edit, @item
  end

  def update
    authorize! :update, @item
    if @item.update item_params
      redirect_to @item, notice: "Item was Successfully Updated"
    else
      flash[:danger] = "Item could not be updated"
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, @item
    @item.destroy
    redirect_to '/#/items', notice: "Item was Successfully Destroyed"
  end

  private

  def get_item
    @item = Item.includes(:projections).find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :link, :max_price, :min_price, :picture, :image, images_attributes: [:picture, :id])
  end
end

app/views/items/_form.html.haml
.container
  = simple_nested_form_for @item, :html => { :class => 'form-horizontal' } do |f|
    .col-lg-4.form-group
      = f.input :title, autofocus: true, class: 'form-control'
      = f.input :description, input_html: { rows: '10', cols: '40'}, class: 'form-control'
    .col-lg-4.form-group.colMid
      %h4
        Set Your Item's Range
      = f.input :max_price, label: "Maximum Price"
      = f.input :min_price, label: "Minimum Price"
      = f.input :link, label: 'Link To Your Website'
    .col-lg-4.form-group.pull-right
      = f.fields_for :images do |j|
        =j.input :picture, label: "Upload Product Images"
        = j.link_to_remove do
          %i.fa.fa-times  Remove Image
          %hr
      = f.link_to_add :images do
        %i.fa.fa-check Add An Image
    .col-lg-12= f.button :submit, :class => 'btn btn-primary'

app/views/items/edit.html.haml
%h1 this is the edit page
=render 'items/form'

app/views/items/index.html.haml
.container
  .col-lg-12
    %input.search.col-lg-5.pull-right{'ng-model' => 'searchText', 'ng-model-options' => '{debounce: 500}', "placeholder" => "Search by Title or Description", 'autofocus' => true} 
    %div.col-lg-5.sort{'ng-controller' => 'DropdownCtrl'}
      %div{'class' => 'btn-group', 'dropdown' => '', 'is-open' => 'status.isopen'}
        %button{ 'type' => 'button', 'class' => 'btn btn-primary dropdown-toggle', 'ng-disabled' => 'disabled' } 
          Sorting By: {{orderTitle | capitalize}}
          %i.fa.fa-caret-down.fa-lg.pull-right
        %ul.pull-right{'class' => 'dropdown-menu', 'role' => 'menu'}
          %li{'ng-repeat' => 'choice in choices'}
            %a{'ng-click' => 'sort( choice )'} {{choice | capitalize}}
  %br
  %br
  .col-lg-3{'ng-repeat' => 'item in items | filter:searchText | orderBy: order:true'  }
    %a{"href" => "/#/items/{{item.id}}"}
      %img{"ng-src" => "{{item.images[0].url}}"}
    %a{"href" => "/#/items/{{item.id}}"}
      %h4 {{item.title}}
      %div{'ng-if' => 'item.days_remaining < 1'}
        %h5 Closed
      %div{'ng-if' => 'item.days_remaining == 1'}
        %h5 {{item.days_remaining}} Day Remaining
      %div{'ng-if' => 'item.days_remaining > 1'}
        %h5 {{item.days_remaining}} Days Remaining
    %p {{item.description | limitTo: 95 }}
  -#@items.each do |item|
    %h4= link_to item.title, item_path(item)
    %h5= item.description

app/views/items/new.html.haml
%h1 Post A New Item
= render 'items/form'

app/views/items/show.html.haml
%h1 {{item.title}}
%div{'ng-if' => 'item.days_remaining < 1'}
  %h3 Closed
%div{'ng-if' => 'item.days_remaining == 1'}
  %h3 {{item.days_remaining}} Day Remaining
%div{'ng-if' => 'item.days_remaining > 1'}
  %h3 {{item.days_remaining}} Days Remaining
.col-lg-offset-4.col-lg-4
  .progress{'ng-if' => 'item.days_remaining == 6'}
    .progress-bar{'role' => 'progressbar', 'aria-valumin' => '0', 'aria-valumax' => '7', 'style' => 'width: 15%'} Day 1
  .progress{'ng-if' => 'item.days_remaining == 5'}
    .progress-bar{'role' => 'progressbar', 'aria-valumin' => '0', 'aria-valumax' => '7', 'style' => 'width: 30%'} Day 2
  .progress{'ng-if' => 'item.days_remaining == 4'}
    .progress-bar{'role' => 'progressbar', 'aria-valumin' => '0', 'aria-valumax' => '7', 'style' => 'width: 43%'} Day 3
  .progress{'ng-if' => 'item.days_remaining == 3'}
    .progress-bar{'role' => 'progressbar', 'aria-valumin' => '0', 'aria-valumax' => '7', 'style' => 'width: 58%'} Day 4
  .progress{'ng-if' => 'item.days_remaining == 2'}
    .progress-bar{'role' => 'progressbar', 'aria-valumin' => '0', 'aria-valumax' => '7', 'style' => 'width: 70%'} Day 5
  .progress{'ng-if' => 'item.days_remaining == 1'}
    .progress-bar{'role' => 'progressbar', 'aria-valumin' => '0', 'aria-valumax' => '7', 'style' => 'width: 85%'} Last Day!
  .progress{'ng-if' => 'item.days_remaining <= 0 '}
    .progress-bar{'role' => 'progressbar', 'aria-valumin' => '0', 'aria-valumax' => '7', 'style' => 'width: 100%'} Item Closed! Thanks For Your Support
.container
  %div.col-lg-offset-2.col-lg-8.col-lg-offset-2{'ng-controller' => 'CarouselDemoCtrl'}
    %div{'style' => 'height: 300px'}
      %carousel{'interval' => 'myInterval'}
        %slide{'ng-repeat' => 'slide in item.images', 'active' => 'slide.active'}
          %img{'ng-src' => '{{slide.image}}', 'style' => 'margin:auto;'}
  %br
  %p.col-lg-offset-2.col-lg-8.col-lg-offset-2 {{item.description}}
  %div{'ng-if' => 'item.current_user == "blank"'}
    %h3.col-lg-offset-2.col-lg-8.col-lg-offset-2 You Must Be Signed In To Estimate a Price
  %div{'ng-if' => 'item.email != item.current_user' }
    %div{'ng-if' => 'item.is_old'}
      %h3.col-lg-offset-2.col-lg-8.col-lg-offset-2 {{item.title}}'s Week Has Expired. Thank You For Your Support!
    %div{'ng-if' => 'item.is_old == false'}
      %div{'ng-if' => 'item.current_user != "blank" '}
        %div{'ng-controller' => 'ProjCtrl'}
          %form.col-lg-12.css-form.well{'ng-submit' => "project(item, proj)", 'name' => 'projection', 'ng-hide' => 'item.has_projected'}
            .form-group
              %label How Much Would You Pay For {{item.title}}? 
              %input{'required' => true, 'ng-model' => 'proj.price', 'type' => 'number', 'min' => '0', 'ng-model-options' => "{ debounce: 500}"}
              %br
              %label Would You Like to Receive Email Updates?
              %input{'ng-model' => 'proj.mail', 'type' => 'checkbox', 'checked' => true}
            .innerWell{'ng-if' => 'proj.price'}
              %h3{'ng-if' => 'proj.price' } I Would Pay {{proj.price | currency}} For {{item.title}}
              %h3{'ng-if' => 'proj.price && proj.mail'} I Would Like to Receive Email Updates
              %h3{'ng-if' => 'proj.price && !proj.mail'} I Would Not Like to Receive Email Updates
              %button.btn.btn-primary{ 'type' => 'submit', 'ng-disabled' => 'projection.$invalid'} Submit Your Projection
  =# @item.title
  =# @item.description
  =# "Posted by: #{@item.artist.email}"
  -# TODO Add users can link to their personal selling site
  -#@item.images.each do |image|
    =link_to image_tag(image.picture.url(:medium)), image.picture.url
  -#if closed @item
    %h3 This Item has exceeded the 7 Day Projection Week
  -#else
    - if not_artist(@item) && not_banned
      = simple_form_for @projection, :html => { class: 'form-horizontal' } do |f|
        = f.hidden_field :item_id, value: @item.id
        = f.input :price
        = f.input :mail, label: "Would You Like to Receive Updates About #{@item.title}"
        = f.button :submit, :class => 'btn-success'

  -# if is_artist
    -@item.projections.each do |p|
      %h5= number_to_currency p.price
%div{'ng-if' => 'item.email == item.current_user && item.projections.length > 0'}
  %table.table.table-striped
    %thead
      %tr
        %th Price
        %th Want Email Updates?
    %tbody
      %tr{'ng-repeat' => 'p in item.projections'}
        %td {{p.projection.price}}
        %td {{p.projection.mail}}
      %hr
      %tr
        %td 
          %b Average(with range)
        %td {{item.average}}
      %tr
        %td 
          %b Average
        %td {{item.entire_average}}